In [1]:
import pandas as pd

In [2]:
df1 = pd.DataFrame({
    'first_name': ['Peter', 'Tony', 'Steve'],
    'last_name': ['Parker', 'Stark', 'Rogers'],
    'role': ['Spider-Man', 'Iron-Man', 'Captain America']
}, index = [0, 1, 2])

In [3]:
df2 = pd.DataFrame({
    'first_name': ['Frank', 'Matthew'],
    'last_name': ['Castle', 'Murdock'],
    'role': ['The Punisher', 'Daredevil']
}, index = [3, 4])

In [4]:
df3 = pd.DataFrame({
    'first_name': ['Bruce', 'Bruce'],
    'last_name': ['Banner', 'Wayne'],
    'role': ['The Hulk', 'Batman']
}, index = [5, 6])

In [5]:
pd.concat([df1, df2, df3]) # concatenates data frames

  first_name last_name             role
0      Peter    Parker       Spider-Man
1       Tony     Stark         Iron-Man
2      Steve    Rogers  Captain America
3      Frank    Castle     The Punisher
4    Matthew   Murdock        Daredevil
5      Bruce    Banner         The Hulk
6      Bruce     Wayne           Batman

In [6]:
# You can concatenate along columns by specifying axis = 1

In [7]:
left = pd.DataFrame({
    'first_name': ['Peter', 'Tony', 'Steve', 'Frank', 'Matthew', 'Bruce', 'Bruce'],
    'last_name': ['Parker', 'Stark', 'Rogers', 'Castle', 'Murdock', 'Banner', 'Wayne']
})
left.index.names = ['ID']
left

   first_name last_name
ID
0       Peter    Parker
1        Tony     Stark
2       Steve    Rogers
3       Frank    Castle
4     Matthew   Murdock
5       Bruce    Banner
6       Bruce     Wayne

In [8]:
right = pd.DataFrame({
    'role': ['Spider-Man', 'Iron-Man', 'Captain America', 'The Punisher', 'Daredevil', 'The Hulk', 'Batman']
})
right.index.names = ['ID']
right

               role
ID
0        Spider-Man
1          Iron-Man
2   Captain America
3      The Punisher
4         Daredevil
5          The Hulk
6            Batman

In [9]:
pd.merge(left, right, how = 'inner', on = 'ID') # merges two data frames on 'ID' (similar to SQL)

   first_name last_name             role
ID
0       Peter    Parker       Spider-Man
1        Tony     Stark         Iron-Man
2       Steve    Rogers  Captain America
3       Frank    Castle     The Punisher
4     Matthew   Murdock        Daredevil
5       Bruce    Banner         The Hulk
6       Bruce     Wayne           Batman

In [10]:
# Joining is a convenient method for combining the columns of two data frames ON YOUR INDEX

In [11]:
left = pd.DataFrame({
    'first_name': ['Peter', 'Tony', 'Steve', 'Frank', 'Matthew', 'Bruce', 'Bruce'],
    'last_name': ['Parker', 'Stark', 'Rogers', 'Castle', 'Murdock', 'Banner', 'Wayne']
})
right = pd.DataFrame({
    'role': ['Spider-Man', 'Iron-Man', 'Captain America', 'The Punisher', 'Daredevil', 'The Hulk', 'Batman']
})
left.join(right)

  first_name last_name             role
0      Peter    Parker       Spider-Man
1       Tony     Stark         Iron-Man
2      Steve    Rogers  Captain America
3      Frank    Castle     The Punisher
4    Matthew   Murdock        Daredevil
5      Bruce    Banner         The Hulk
6      Bruce     Wayne           Batman